android_binary(
    name = "app",
    manifest = "AndroidManifest.xml",
    resource_files = glob(["res/**"]),
    srcs = [
        "MyActivity.java",
    ],
    deps = [
        "//third_party:butterknife_runtime",
        "//third_party:butterknife_processor",
    ],
)
